<Project Sdk="Microsoft.NET.Sdk;Lucent.Lui.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <SelfContained>true</SelfContained>
    <RootNamespace>LightNotes</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../LightNotes.Storage/LightNotes.Storage.csproj" />
    <PackageReference Include="Lucent.Platform.Windows" Version="[$(LucentVersion)]" />
    <PackageReference Include="Lucent.Hosting" Version="[$(LucentVersion)]" />
    <None
      Include="../../notices/*"
      Link="notices/%(Filename)%(Extension)"
      CopyToOutputDirectory="PreserveNewest"
      CopyToPublishDirectory="PreserveNewest"
    />
  </ItemGroup>
</Project>
