<Project>
  <PropertyGroup>
    <LucentVersion Condition="'$(LucentVersion)' == ''">0.3.0-dev.36.1</LucentVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>10.0-Recommended</AnalysisLevel>
    <IsAotCompatible>true</IsAotCompatible>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
