<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <IsAotCompatible>false</IsAotCompatible>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../tools/LightNotes.Review/ReviewSamples.cs" Link="ReviewSamples.cs" />
    <ProjectReference Include="../../src/LightNotes/LightNotes.csproj" />
  </ItemGroup>
</Project>
